@REM ************************************************************************************
@REM Author: Rui Moreira
@REM Date: 20/02/2009
@REM http://docs.oracle.com/javase/tutorial/rmi/running.html
@REM ************************************************************************************

@REM ======================== Use Shell Parameters ========================
@REM Script usage: setenv <role> (where role should be: server / client)
@SET SCRIPT_ROLE=%1


@REM ==== JAVA NAMING STUFF ====
@Set JAVAPROJ_NAME=DistributedMinesweeper
@set JAVAPROJ=%CD%\..
@Set PACKAGE=Minesweeper
@Set SERVICE_NAME_ON_REGISTRY=MinesweeperService
@Set CLIENT_CLASS_PREFIX=Minesweeper
@Set SERVER_CLASS_PREFIX=Minesweeper
@Set CLIENT_CLASS_POSTFIX=Client
@Set SERVER_CLASS_POSTFIX=Server
@Set SETUP_CLASS_POSTFIX=Setup
@Set SERVANT_IMPL_CLASS_POSTFIX=Impl
@Set SERVANT_ACTIVATABLE_IMPL_CLASS_POSTFIX=ActivatableImpl

@REM ==== NETWORK STUFF ====
@Set REGISTRY_HOST=localhost
@Set REGISTRY_PORT=1099
@Set SERVER_RMI_HOST=%REGISTRY_HOST%
@Set SERVER_RMI_PORT=1098
@Set SERVER_CODEBASE_HOST=%SERVER_RMI_HOST%
@Set SERVER_CODEBASE_PORT=8000
@Set CLIENT_RMI_HOST=%REGISTRY_HOST%
@Set SERVER_BACKUP_RMI_PORT=1097
@Set CLIENT_RMI_PORT=1096
@Set CLIENT_CODEBASE_HOST=%CLIENT_RMI_HOST%
@Set CLIENT_CODEBASE_PORT=8000

@REM ======================== DO NOT CHANGE AFTER THIS POINT ========================
@Set JAVAPACKAGE=%PACKAGE%
@Set JAVAPACKAGEROLE=%PACKAGE%.%SCRIPT_ROLE%
@Set JAVAPACKAGEPATH=%PACKAGE%/%SCRIPT_ROLE%
@Set JAVASCRIPTSPATH=%PACKAGE%/runscripts
@Set JAVASECURITYPATH=%PACKAGE%\\securitypolicies
@Set SERVICE_NAME=%SERVICE_PREFIX%Service
@Set SERVICE_URL=rmi://%REGISTRY_HOST%:%REGISTRY_PORT%/%SERVICE_NAME%
@Set SERVANT_ACTIVATABLE_IMPL_CLASS=%JAVAPACKAGEROLE%.%SERVER_CLASS_PREFIX%%SERVANT_ACTIVATABLE_IMPL_CLASS_POSTFIX%
@Set SERVANT_PERSISTENT_STATE_FILENAME=%SERVICE_PREFIX%Persistent.State


@Set NETBEANS_CLASSES=build/classes/
@Set NETBEANS_SRC=src
@Set NETBEANS_DIST=dist
@Set NETBEANS_DIST_LIB=dist/lib

@set JAVAPROG_CLASSES_FOLDER=%JAVAPROJ%\%NETBEANS_CLASSES%
@set JAVAPROJ_DIST_FOLDER=%JAVAPROJ%\%NETBEANS_DIST%
@set JAVAPROJ_JAR_FILE=%JAVAPROJ_NAME%.jar

@set CLASSPATH=.;%JAVAPROG_CLASSES_FOLDER%


@Set ABSPATH2CLASSES=%JAVAPROJ%\%NETBEANS_CLASSES%
@Set ABSPATH2SRC=%JAVAPROJ%\%NETBEANS_SRC%
@Set ABSPATH2DIST=%JAVAPROJ%/%NETBEANS_DIST%


@Set SERVER_CODEBASE=http://%SERVER_CODEBASE_HOST%:%SERVER_CODEBASE_PORT%/%JAVAPROJ_JAR_FILE%
@Set CLIENT_CODEBASE=http://%CLIENT_CODEBASE_HOST%:%CLIENT_CODEBASE_PORT%/%JAVAPROJ_JAR_FILE%


@Set SERVER_SECURITY_POLICY=file:///%JAVAPROJ%\\%NETBEANS_SRC%\\%JAVASECURITYPATH%\\serverAllPermition.policy
@Set CLIENT_SECURITY_POLICY=file:///%JAVAPROJ%\\%NETBEANS_SRC%\\%JAVASECURITYPATH%\\clientAllPermition.policy
@Set SETUP_SECURITY_POLICY=file:///%JAVAPROJ%\\%NETBEANS_SRC%\\%JAVASECURITYPATH%\\setup.policy
@Set RMID_SECURITY_POLICY=file:///%JAVAPROJ%\\%NETBEANS_SRC%\\%JAVASECURITYPATH%\\rmid.policy
@Set GROUP_SECURITY_POLICY=file:///%JAVAPROJ%\\%NETBEANS_SRC%\\%JAVASECURITYPATH%\\group.policy

